config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users
  root to: "patients#index"
  get 'profile', to: 'profiles#show', as: :profile
  get 'admin', to: 'admin#index', as: :admin
  namespace :admin do
    resources :doctors
  end
  resources :doctors
  resources :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/nameable.rb
module Nameable
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  include Nameable
  validates :first_name, :last_name, :speciality, :contact_phone, :gps, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  include Nameable
  belongs_to :user
  validates :first_name, :last_name, :contact_phone, :gps, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :patients
end

app/controllers/admin/doctors_controller.rb
=begin
 TODO: 
 - tried moving common concern methods shared with controllers/doctors_controller
   into concerns/doctors/controller_concers with no luck
 - two controllers for doctor seems like a bad thing
 - need to identify use cases for user, doctor, and admin and determine how to divide
   these into controller responsibilities
 DRG 2/6/16
=end
class Admin::DoctorsController < AdminController

  # TODO: duplicates controllers/doctors_controller.rb
  def index
    @doctors = Doctor.all.order(:last_name)
  end

  # TODO: duplicates controllers/doctors_controller.rb
  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    @doctor.gps = location_not_known #replace with gps service for real-time location

    if @doctor.save
      flash[:notice] = 'Doctor registered.'
      redirect_to :action => 'show', :id => @doctor.id
    else
      flash[:alert] = 'Doctor not registered.'
      render 'new'
    end
  end

  private

  def doctor_params
    params.require(:doctor).permit(
      :first_name,
      :last_name,
      :speciality,
      :contact_phone)
  end

  def location_not_known
     '{"lat": 32.222605, "lng": -110.974710}'
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :require_admin

protected

  def require_admin
    unless admin?
      flash[:error] = "You do not have sufficient privileges for the requested action"
      redirect_to '/'
    end
  end

  def admin?
    !current_user.nil? && current_user.admin?
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all.order(:last_name)
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    @doctor.gps = location_not_known #replace with gps service for real-time location

    if @doctor.save
      flash[:notice] = 'Doctor registered.'
      redirect_to @doctor
    else
      flash[:alert] = 'Doctor not registered.'
      render 'new'
    end
  end

  private

  def doctor_params
    params.require(:doctor).permit(
      :first_name,
      :last_name,
      :speciality,
      :contact_phone)
  end

  def location_not_known
     '{"lat": 32.222605, "lng": -110.974710}'
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new, :create]

  def index
    if user_has_patient?
      @patient_gps = current_user.patients.first.gps
      @patient = current_user.patients.first
    else
      @patient_gps = location_not_known
    end
    @doctors = Doctor.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.user = current_user
    @patient.gps = location_not_known ## replace with Geolocation service call

    if @patient.save
      flash[:notice] = 'Patient registered.'
      redirect_to @patient
    else
      flash[:alert] = 'Patient not registered.'
      render 'new'
    end
  end

  private

  def patient_params
    params.require(:patient).permit(
      :first_name,
      :last_name,
      :contact_phone)
  end

  def location_not_known
     '{"lat": 32.222605, "lng": -110.974710}'
  end

  def user_has_patient?
    current_user && current_user.patients.any?
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @patients = current_user.patients
  end
end

app/helpers/admin/doctors_helper.rb
module Admin::DoctorsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/doctors/index.html.erb
<header>
  <h1>Doctors</h1>
  <ul class="actions">
    <li><%= link_to "Add new doctor", new_admin_doctor_path, class: "new" %></li>
  </ul>
</header>

<div id="doctors">
  <% @doctors.each do |doctor| %>
      <h2><%= link_to doctor.last_name, doctor_path(doctor) %> </h2>
      <div id="doctor">
        <%= doctor.full_name %></br>
        <%= doctor.speciality %></br>
        <%= doctor.contact_phone %></br>
      </div>
  <% end %>
</div>

app/views/admin/doctors/new.html.erb
<header>
  <h1>New Doctor registration</h1>
</header>
<%= simple_form_for @doctor, :url => url_for(:action => 'create', :controller => 'admin/doctors') do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :speciality %>
  <%= f.input :contact_phone %>
  <%= f.submit "Register", class: "btn-primary" %>
<% end %>

app/views/admin/doctors/show.html.erb
<header>
  <h1><%= @doctor.last_name %></h1>
</header>

<div id="doctor">
  <%= @doctor.full_name %></br>
  <%= @doctor.speciality %></br>
  <%= @doctor.contact_phone %></br>
</div>

app/views/admin/index.html.erb
<header>
  <h1>Administration</h1>
  <ul class="actions">
    <li><%= link_to "Doctor Accounts", admin_doctors_path, class: "new" %></li>
  </ul>
</header>

app/views/doctors/index.html.erb
<header>
  <h1>Doctors</h1>
</header>


<div id="doctors">
  <% @doctors.each do |doctor| %>
      <h2><%= link_to doctor.last_name, doctor_path(doctor) %> </h2>
      <div id="doctor">
        <%= doctor.full_name %></br>
        <%= doctor.speciality %></br>
        <%= doctor.contact_phone %></br>
      </div>
  <% end %>
</div>

app/views/doctors/new.html.erb
<header>
  <h1>New Doctor registration</h1>
</header>
<%= simple_form_for(@doctor) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :speciality %>
  <%= f.input :contact_phone %>
  <%= f.submit "Register", class: "btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Better On Call</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%=Rails.configuration.x.google_js_api_key%>&callback=initMap"
          async defer></script>

  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Better On Call", root_path, class: "navbar-brand" %>
          <button type="button" class="navbar-toggle collapsed"
            data-toogle="collapse" data-target="#collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="collapse">
          <ul class="nav navbar-nav">
            <li class="<%= "active" if current_page?("/") %>">
              <%= link_to "Home", root_path %>
            </li>
            <% unless user_signed_in? %>
            <li class="<%= "active" if current_page?("/users/sign_up") %>">
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li class="<%= "active" if current_page?("/users/sign_in") %>">
              <%= link_to "Sign in", new_user_session_path %>
            </li>
            <% end %>
            <% if user_signed_in? %>
              <% if current_user.admin? %>
            <li class="<%= "active" if current_page?("/admin")  %>">
              <%= link_to "Admin", admin_path %>
            </li>
              <% end %>
            <li class="<%= "active" if current_page?("/profile")  %>">
              <%= link_to "Profile", profile_path %>
            </li>
            <% end %>
          </ul>
            <% if user_signed_in? %>
              <div class="navbar-right">
                <p class="navbar-text">
                  Signed in as <%= current_user.email %>
                </p>
                <ul class="nav navbar-nav">
                  <li><%= link_to "Sign out", destroy_user_session_path,
                    method: :delete %>
                  </li>
                </ul>
              </div>
            <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key %>"><%= message %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= simple_form_for(patient) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :contact_phone %>
  <%= f.submit "Register", class: "btn-primary" %>
<% end %>

app/views/patients/index.html.erb
<header>
  <h1>Find a Doctor nearby</h1>
  <ul class="actions">
    <% if user_signed_in? %>
      <li><%= link_to "Register as new patient", new_patient_path, class: "new" %></li>
      <li><%= link_to "Doctors", doctors_path, class: "new" %></li>
    <% end %>
  </ul>
</header>


<div id="map" data-patient_gps="<%= @patient_gps %>"></div>

<% if @patient %>
  <div id="patient" style="display: none;">
    <h2><%= link_to @patient.last_name, patient_path(@patient) %></h2>
      <p id="full_name"><%= @patient.full_name %></p>
      <p id="contact_phone"><%= @patient.contact_phone %></p>
  </div>
  <% else %>
    <div id="patient" style="display: none;">
      <p>
        To view your location:
        <%= link_to "Sign in", new_user_session_path %>
        or
        <%= link_to "Sign up", new_user_registration_path %>
      </p>
    </div>
<% end %>

<div id="doctors">
  <% @doctors.each do |doctor| %>
    <div id="doctor_<%= doctor.id %>" style="display: none;">
      <h2><%= link_to "Dr. #{doctor.last_name}", doctor_path(doctor) %></h2>
      <p id="full_name">Dr. <%= doctor.full_name %>, MD</p>
      <p id="speciality"><%= doctor.speciality %></p>
      <p id="contact_phone"><%= doctor.contact_phone %></p>
      <p id="gps" style="display: none;"><%= doctor.gps %></p>
    </div>
  <% end %>
</div>

app/views/patients/new.html.erb
<header>
  <h1>New Patient registration</h1>
</header>

<%= render 'form', patient: @patient %>

app/views/patients/show.html.erb
<header>
  <h1><%= @patient.last_name %></h1>
</header>

<div id="patient">
  <%= @patient.full_name %></br>
  <%= @patient.contact_phone %></br>
</div>

app/views/profiles/show.html.erb
<header>
  <h1>Profile</h1>
  <ul class="actions">
    <li><%= link_to "Register a new patient", new_patient_path, class: "new" %></li>
  </ul>
</header>

<h2>Patients</h2>
<div id="patients">
  <% @patients.each do |patient| %>
      <h2><%= link_to patient.full_name, patient_path(patient) %> </h2>
      <div id="patient">
        <%= patient.full_name%></br>
        <%= patient.contact_phone %></br>
      </div>
  <% end %>
</div>